name: CI
permissions:
  contents: write
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "${{ matrix.platform }} with Java ${{ matrix.java-distribution }} version ${{ matrix.java-version }}"
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        java-distribution:
          - adopt-hotspot
          - temurin
          - zulu
        java-version:
          - 8
          - 11
        include:
          - platform: windows-latest
            java-distribution: adopt-hotspot
            java-version: 11
          - platform: macos-latest
            java-distribution: adopt-hotspot
            java-version: 11
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate and submit dependency graph
        if: ${{ github.event_name == 'push' }}
        uses: gradle/actions/dependency-submission@v4
      - name: Build
        run: ./gradlew -i -S build
      - name: Tomcat Install
        run: ./gradlew -i -S tomcatInstall
      - name: Start Tomcat
        run: ./gradlew -i -S tomcatStart
      - name: Stop Tomcat
        run: ./gradlew -i -S tomcatStop
      - name: Clear Logs Tomcat
        run: ./gradlew -i -S tomcatClearLogs
      - name: Start Database
        run: ./gradlew -i -S hsqlStart
      - name: Init Data
        run: ./gradlew -i -S dataInit
      - name: Stop Database
        run: ./gradlew -i -S hsqlStop
      - name: Generate Skin
        run: ./gradlew -i -S skinGenerate -DskinName=test
